apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exercise1
  template:
    metadata:
      labels:
        app: exercise1
    spec:
      containers:
      - name: exercise1
        image: kralevski12/exercise1:${BUILD_NUMBER}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: exercise1-service
spec:
  selector:
    app: exercise1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
